### ISSUE TITLE
Animego Source (anti ddos)

### ISSUE THREAD

**Issue by vastonld** [vypivshiy/anicli-api#32]
Начало выдавать ошибку (403) на animego. Регает anti ddos

Лог:

[1] DDOSServerDetectError: 'ddos-guard' detected, <Request('GET', 'https://animego.org/search/anime?q=%D0%9F%D0%BB%D0%B0%D1%87%D1%83%D1%89%D0%B8%D0%B9%20%D0%BF%D1%80%D0%B8%D0%B7%D1%80%D0%B0%D0%BA%20%D0%BD%D0%B0%20%D0%BF%D0%B5%D0%BD%D1%81%D0%B8%D0%B8')> -> <Response [403 Forbidden]> try again
WARNING:anicli-api:[1] DDOSServerDetectError: 'ddos-guard' detected, <Request('GET', 'https://animego.org/search/anime?q=%D0%9F%D0%BB%D0%B0%D1%87%D1%83%D1%89%D0%B8%D0%B9%20%D0%BF%D1%80%D0%B8%D0%B7%D1%80%D0%B0%D0%BA%20%D0%BD%D0%B0%20%D0%BF%D0%B5%D0%BD%D1%81%D0%B8%D0%B8')> -> <Response [403 Forbidden]> try again

**Comment by vypivshiy** [comment]
По логам в middleware проблема (не учел кейс, когда со стороны владельца
сайт закрыт)
Конкретно этот источник несколько дней не работает в том числе через
ВПН/прокси

https://downdetector.su/animego

пн, 16 дек. 2024 г., 00:37 vastonld ***@***.***>:

**Comment by vastonld** [comment]
А, ну да. animego.ong щас

**Comment by vastonld** [comment]
И структура сайта чуть поменялась. Этим скриптом с другим доменом уже не ищет. Будет апдейт?

**Comment by vastonld** [comment]
Апдейт будет?

**Comment by vypivshiy** [comment]
обновил новый домен источника
